import { NextResponse } from 'next/server';
import { getServiceSupabase } from '@/utils/supabaseClientSingleton';
import { generateAiContent } from '@/lib/ai';
import { withAdminAuth } from '@/lib/auth/withAdminAuth';

export const dynamic = 'force-dynamic';

export const POST = withAdminAuth(async (request, user) => {
    try {
        const supabaseUrl = process.env.SUPABASE_URL;
        const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

        if (!supabaseUrl || !supabaseKey || process.env.SUPABASE_ENABLED !== 'true') {
            return NextResponse.json({ error: 'Supabase required for AI Growth.' }, { status: 400 });
        }

        const supabase = getServiceSupabase();
        const { action } = await request.json(); // 'campaigns', 'forecast', 'suggestions'

        if (action === 'campaigns') {
            const { data: traffic } = await supabase.from('traffic_sources').select('*').limit(10);
            const prompt = "Analyze these traffic sources. Return an array of valid JSON objects exactly matching: [ { \"source\": \"string\", \"campaign\": \"string\", \"ai_insight\": \"detailed insight\" } ]";
            const resText = await generateAiContent(prompt, JSON.stringify(traffic));
            const parsed = extractJsonArray(resText);
            for (const item of parsed) {
                await supabase.from('campaign_insights').insert({
                    source: item.source || 'General', campaign: item.campaign || '-', ai_insight: item.ai_insight
                });
            }
            return NextResponse.json({ success: true, insights: parsed });
        }

        if (action === 'forecast') {
            const { count: leadsCount } = await supabase.from('leads').select('*', { count: 'exact', head: true });
            const prompt = "Act as predictive analytics AI. Based on the fact we have " + leadsCount + " total leads so far, predict next week's expected leads and conversions. Return ONE valid JSON object exactly matching: { \"expected_leads\": number, \"expected_conversions\": number, \"ai_reasoning\": \"string\" }";
            const resText = await generateAiContent(prompt, "");
            const parsed = extractJsonObject(resText);

            // next week date
            const nextWeek = new Date();
            nextWeek.setDate(nextWeek.getDate() + 7);

            const { data: inserted } = await supabase.from('conversion_forecasts').insert({
                forecast_date: nextWeek.toISOString(),
                expected_leads: parsed.expected_leads || 0,
                expected_conversions: parsed.expected_conversions || 0,
                ai_reasoning: parsed.ai_reasoning || "Generated by simulation"
            }).select().single();

            return NextResponse.json({ success: true, forecast: inserted });
        }

        if (action === 'suggestions') {
            const prompt = "Act as a growth hacker AI. Suggest 3 new growth strategies (e.g. blog topics, calculators) for our insurance agency platform. Return an array of valid JSON objects: [ { \"suggestion_type\": \"blog_topic | resource | calculator | feature\", \"title\": \"string\", \"description\": \"string\", \"potential_impact\": \"high | medium | low\" } ]";
            const resText = await generateAiContent(prompt, "");
            const parsed = extractJsonArray(resText);

            for (const item of parsed) {
                await supabase.from('growth_suggestions').insert({
                    suggestion_type: item.suggestion_type || 'feature',
                    title: item.title,
                    description: item.description,
                    potential_impact: item.potential_impact
                });
            }
            return NextResponse.json({ success: true, suggestions: parsed });
        }

        return NextResponse.json({ error: 'Invalid action' }, { status: 400 });

    } catch (error) {
        console.error('AI Growth Engine Error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
});

export const GET = withAdminAuth(async (request, user) => {
    try {
        const supabaseUrl = process.env.SUPABASE_URL;
        const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
        if (!supabaseUrl || !supabaseKey || process.env.SUPABASE_ENABLED !== 'true') {
            return NextResponse.json({ campaigns: [], forecasts: [], suggestions: [] });
        }

        const supabase = getServiceSupabase();

        const [cRes, fRes, sRes] = await Promise.all([
            supabase.from('campaign_insights').select('*').order('generated_at', { ascending: false }).limit(5),
            supabase.from('conversion_forecasts').select('*').order('generated_at', { ascending: false }).limit(5),
            supabase.from('growth_suggestions').select('*').order('created_at', { ascending: false }).limit(10)
        ]);

        return NextResponse.json({
            campaigns: cRes.data || [],
            forecasts: fRes.data || [],
            suggestions: sRes.data || []
        });
    } catch (err) {
        return NextResponse.json({ error: "Failed to fetch AI growth data" }, { status: 500 });
    }
});

// Helpers
function extractJsonArray(text) {
    try {
        let clean = text.trim();
        if (clean.startsWith('```json')) clean = clean.substring(7, clean.length - 3).trim();
        else if (clean.startsWith('```')) clean = clean.substring(3, clean.length - 3).trim();
        return JSON.parse(clean);
    } catch { return []; }
}
function extractJsonObject(text) {
    try {
        let clean = text.trim();
        if (clean.startsWith('```json')) clean = clean.substring(7, clean.length - 3).trim();
        else if (clean.startsWith('```')) clean = clean.substring(3, clean.length - 3).trim();
        return JSON.parse(clean);
    } catch { return {}; }
}
